language: php
sudo: false

php:
  - 7.1

before_script:
  - composer self-update
  - composer install
  - cp phpunit.xml.dist phpunit.xml

script:
  - ./vendor/bin/parallel-lint src tests
#  - ./vendor/bin/phpcs --standard=ruleset.xml src tests
#  - ./vendor/bin/phpunit --coverage-text
  - php -i