language: php
sudo: false

php:
  - 7.1

before_script:
  - composer self-update
  - composer install

script:
#  - ./vendor/bin/phpcs --standard=ruleset.xml src tests
  - ./vendor/bin/phpunit tests --verbose
  - php -i